# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_PATCH_VERSION
# Uses a more common 2-digit versioning in Jenkins weekly releases.
version-template: $MAJOR.$MINOR
tag-template: jenkins-$NEXT_MINOR_VERSION

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression  
  - title: 📝 Documentation updates
    label: documentation
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 👻 Maintenance
    label: chore
  # TODO: consider merging category or changing emojis
  - title: 🚦 Internal changes
    label: internal
  - title: 🚦 Tests
    labels: 
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
change-template: |
  - type: todo
    message: $TITLE
    pull: $NUMBER
    authors: 
      - $AUTHOR
template: |
  ```yaml
  $CHANGES
  ```
replacers:
  #TODO: How does one add a line break here?
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: |
      - issue: $1
      
